version: '2'
services:
  redis:
    image: redis
  couchdb:
    image: couchdb
    ports:
      - "5001:5984"
    volumes:
      - "./couchdb:/usr/local/var/lib/couchdb"
  nginx:
    image: nginx
    links:
      - node
      - couchdb
    ports:
      - "5000:80"
  node:
    build: ./node_server
    volumes:
      - "./node_server:/usr/src/app"
    links:
      - couchdb
      - redis
    ports:
      - "5002:3000"
